#!/usr/bin/env bash

export AZURE_COG_PREDICTION_KEY='<YOUR_PREDICTION_KEY>'

export POTHOLE_LOCATION_URL='<IMAGE_CLASSIFIER_URL>'
export POTHOLE_LOCATION_PROJECT_ID='<IMAGE_CLASSIFIER_PROJECT_ID>'
export POTHOLE_LOCATION_ITERATION_ID='<IMAGE_CLASSIFIER_ITERATION_ID>'

export POTHOLE_DETECTION_URL='<OBJECT_DETECTION_URL>'
export POTHOLE_DETECTION_PROJECT_ID='<OBJECT_DETECTION_PROJECT_ID>'
export POTHOLE_DETECTION_ITERATION_ID='<OBJECT_DETECTION_ITERATION_ID>'
